docs: Name Change
geocortex/workflow-activities-elementsxs pull request #19
Opened 2022-01-19 23:02 UTC by connerleverett

Change Geocortex -> VertiGIS Studio and geocortex.com -> vertigisstudio.com

2022-01-20 00:29 UTC, connerleverett commented
To be merged after Feb 14th 2022

2022-01-20 19:09 UTC, kenlyon requested changes

2022-01-20 19:09 UTC, kenlyon commented on README.md
> +This project contains activities for interacting with the [Elements XS REST API](https://salesapi.novotx.com/) in a [VertiGIS Studio Workflow](https://www.vertigisstudio.com/products/geocortex-workfl
Should the product name change here?

2022-01-20 23:12 UTC, connerleverett commented on README.md
> +This project contains activities for interacting with the [Elements XS REST API](https://salesapi.novotx.com/) in a [VertiGIS Studio Workflow](https://www.vertigisstudio.com/products/geocortex-workfl
Updated.

2022-01-26 22:09 UTC, rcooney reviewed
The changes all look good. We just need to wait until https://apps.vertigisstudio.com/workflow/designer/ is live.

2022-01-27 20:56 UTC, kenlyon approved these changes

2022-02-16 16:21 UTC, merged